name: gestion_projects
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  bloc: ^8.1.2
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  drop_down_list: ^0.0.5
  email_validator: ^2.1.17
  equatable: ^2.0.5
  file_picker: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.6
  get: ^4.6.5
  google_fonts: ^4.0.5
  intl: ^0.18.0
  modal_bottom_sheet: ^2.1.2
  multi_select_flutter: ^4.1.3
  printing: ^5.11.0
  provider: ^6.0.5
  qlevar_router: ^1.9.0
  shared_preferences: ^2.1.1
  syncfusion_flutter_charts: ^21.2.6
  syncfusion_flutter_datepicker: ^21.2.6
  syncfusion_localizations: ^21.2.6
  universal_html: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
dependency_overrides:
  http: any
  shared_preferences_windows: any
  path_provider_platform_interface: any
  path_provider_windows: any
  shared_preferences_platform_interface: any
  shared_preferences_linux: any
  ffi: any
  win32: any
  modal_bottom_sheet:
    git:
      url: https://github.com/danReynolds/modal_bottom_sheet.git
      path: modal_bottom_sheet

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/gifs/
